spring:
  application:
    name: smart-residence-activity
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/sra
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/sra
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: SRA_Client
            client-secret: 3nuizxy9yEVM7aydCEaCLbkSP9iw7ID0
            scope: openid

kudago:
  url:  https://kudago.com/public-api/v1.4

sra-auth:
  url: http://localhost:8180/realms/sra