spring:
  application:
    name: smart-residence-activity
  datasource:
    url: jdbc:h2:mem:localdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog-master.yml